version: "3.8"
services:
  emoji-archiver:
    container_name: discord-bot-template
    image: ghcr.io/jonathan-yeagy/discord-bot-template:latest
    restart: always
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - CHANNEL_ID=${CHANNEL_ID}
